#In order Rails knows how to t=connect to your OpenERP server, you should create a file APPLICATION_ROOT/config/ooor.yml
#with the following pattern customized with your OpenERP server URL, your target OpenERP database, your login and password.

development:
  url: http://localhost:8069/xmlrpc         #the OpenERP XML/RPC server
  database: demoapp                   #the OpenERP database you want to connect to
  username: admin
  password: admin
  #models: [res.partner, product.template, product.product, product.category, sale.order, sale.order.line, account.invoice] #you can allow only some models if you like
  bootstrap: true   #true if you want to load OpenObject models (will hit OpenERP server) at startup; else use Ooor.reload!(lambda {}) to reload the Ooor models at any time
  #log_level: 0
  #global_context:
    #'lang': en_US


